version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  og-image-handler:
    lang: golang-http
    handler: ./og-image-handler
    image: ghcr.io/rvramesh/og-image-handler:latest
configuration:
  templates:
    - name : golang-http

